version: '3'
volumes: 
    data:
services: 
    queue:
        restart: always
        image: redis:6.0.8-alpine
        # ports: 
            # - "6379:6379"1
    db:
        image: postgres:13-alpine
        volumes:
            # Data volume
            - data:/var/lib/postgresql/data
            # Scripts
            - ./scripts/database/init.sql:/docker-entrypoint-initdb.d/init.sql
        environment: 
            - POSTGRES_HOST_AUTH_METHOD=trust
    worker:
        #restart: on-failure
        build: worker
        # volumes: 
            # - ./worker:/app
        environment: 
            - REDIS_SERVER_HOST=queue
            - REDIS_SERVER_PORT=6379
        depends_on: 
            - queue
        # command: app.py
    backend:
        # restart: always
        build: backend
        environment: 
            - REDIS_SERVER_HOST=queue
            - REDIS_SERVER_PORT=6379
            - POSTGRES_HOST=db
            - POSTGRES_PORT=5432
            - POSTGRES_DATABASE=fb_dev
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - DEBUG=True
        ports:
            - "5000:5000"
        depends_on: 
            - db
            - queue